version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASS
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - main-network
  web:
    image: $IMAGE_LINK
    container_name: $APP_NAME
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - $SERVER_HOST_PORT:8000
      - '5005:5005'
    environment:
      - SERVER_PORT=8000
      - SPRING_APPLICATION_NAME=$APP_NAME
      - SETTINGS_URL=${URL}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/$POSTGRES_DB
      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASS
    networks:
      - main-network

networks:
  main-network:
    name: $NETWORK_NAME
    driver: bridge
