security:
  user:
    name: root
    password: root
spring:
  data:
    mongodb:
      auto-index-creation: 'true'
      authentication-database: admin
      database: schronisko
      port: '27018'
      host: localhost
  devtools:
    restart:
      quiet-period: 1s
      poll-interval: 2s
  main:
    web-application-type: SERVLET
  jackson:
    serialization:
      write-dates-as-timestamps: false
settings:
  user-service:
    editable-fields:
      - password
      - email
      - firstname
      - lastname
      - roles
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html